[package]
name = "tetris"
version = "0.1.0"
authors = ["Scott Schroeder <scottschroeder@sent.com>"]


[dependencies]
piston = "0.37.0"
piston2d-graphics = "0.26.0"
pistoncore-glutin_window = "0.47.0"
piston2d-opengl_graphics = "0.53.0"

log = "0.4.3"
pretty_env_logger = "0.2.4"
rand = "0.5.4"
